name: kektorial
version: '${project.version}'
main: org.nimbus.kektorial.Kektorial
api-version: '1.20'


commands:
  info:
    description: Eine Info
    alsiases:
  kit:
    description: Ein Kit
  startbingoevent:
    description: Das Event starten
    aliases:
  stopbingoevent:
    description: Das Event stoppen (eigentlich nur für debugging)
    aliases: